Controllers/ActorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Movie_Point.IRepository;
using Movie_Point.Models;
using Movie_Point.ViewModel;

namespace Movie_Point.Controllers
{
    public class ActorController : Controller
    {
        IActor repository;
        public ActorController(IActor repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ShowDetails(int id) 
        { 
            var actor = repository.GetById(id);
            return View(actor); 
        }
        [HttpGet]
        public IActionResult GetAll()
        {
            var actors = repository.ReadAll();
            return View(actors);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View(new ActorViewModel());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult SaveNew(ActorViewModel actor)
        {
            if(ModelState.IsValid)
            {
                var act = new Actor();
                act.FirstName = actor.FirstName;
                act.LastName = actor.LastName;
                act.Bio = actor.Bio;
                act.ProfilePicture = actor.ProfilePicture;
                act.News = actor.News;
                repository.Create(act);
                return RedirectToAction("GetAll");
            }
            return View("Create");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var actor = repository.GetById(id);
            if (actor != null)
            {
                repository.Delete(id);
                return RedirectToAction("GetAll");
            }
            return View("Home", "Error");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var actor = repository.GetById(id);
            if (actor == null)
            {
                return View("GetAll");
            }
            ActorViewModel actorViewModel = new ActorViewModel()
            {
                LastName = actor.LastName,
                FirstName = actor.FirstName,
                Bio = actor.Bio,
                ProfilePicture = actor.ProfilePicture,
                News = actor.News
            };
            return View(actorViewModel);
        }
        //[Authorize(Roles = "Admin")]
        //public IActionResult SaveEdit(ActorViewModel actor)
        //{
        //    if (ModelState.IsValid)
        //    {
        //       var act = repository.GetById(actor.Id);
        //        repository.Update(actor);
        //        return RedirectToAction("GetAlll",act);
        //    }
        //    return View("Edit");
        //}
    }
}

Controllers/CinemaController.cs
using Microsoft.AspNetCore.Mvc;
using Movie_Point.IRepository;

namespace Movie_Point.Controllers
{
    public class CinemaController : Controller
    {
        ICinema cinema;
        public CinemaController(ICinema cinema)
        {
            this.cinema = cinema;
        }
        public IActionResult Index()
        {
            var cinemas = cinema.GetAll();
            return View(cinemas);
        }
        public IActionResult GetMovies(int id)
        {
            var movies = cinema.GetMoviesWithCinemaId(id);
            return View("\\Views\\Movie\\Index.cshtml", movies);
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movie_Point.Data;
using Movie_Point.IRepository;
using Movie_Point.Models;
using Movie_Point.Repository;
using Movie_Point.ViewModel;

namespace Movie_Point.Controllers
{
    public class MovieController : Controller
    {
        //List<Movie> movies = new List<Movie>();
        IMovie repository;
        public MovieController(IMovie repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            var movies =repository.ReadAllWithCinema_Category();
            return View(movies);
        }
        [Authorize( Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["categories"] = repository.GetCategories();
            ViewData["cinemas"] = repository.GetCinemas();
            return View(new MovieViewModel());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult SaveNew(MovieViewModel movie)
        {
            if(ModelState.IsValid)
            {
                var mov = new Movie();
                mov.Name = movie.Name;
                mov.Description = movie.Description;
                mov.Price = movie.Price;
                mov.MovieStatus = movie.MovieStatus;
                mov.StartDate = movie.StartDate;
                mov.EndDate = movie.EndDate;
                mov.CategoryId = movie.CategoryId;
                mov.CinemaId = movie.CinemaId;
                mov.ImgUrl = movie.ImgUrl;
                mov.TrailerUrl = movie.TrailerUrl;
                repository.Create(mov);
                return RedirectToAction("Index");
            }
            return View("Create");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var movie = repository.Get(id);
            if(movie == null)
            {
                return RedirectToAction("Index");
            }
            MovieViewModel movieViewModel = new MovieViewModel() 
            { 
                Name=movie.Name
                ,Id=movie.Id
                ,Description=movie.Description
                ,Price=movie.Price
                ,StartDate=movie.StartDate
                ,EndDate=movie.EndDate
                ,ImgUrl=movie.ImgUrl
                ,TrailerUrl=movie.TrailerUrl
                ,CategoryId=movie.CategoryId
                ,CinemaId=movie.CinemaId
                ,MovieStatus=movie.MovieStatus
            };
            ViewData["categories"] = repository.GetCategories();
            ViewData["cinemas"] = repository.GetCinemas();
            return View(movieViewModel);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult SaveEdit(MovieViewModel movie)
        {
            if (ModelState.IsValid)
            {
                var mov = repository.Get(movie.Id);
                repository.Update(movie);
                return RedirectToAction("Index",mov);
            }
            return View("Edit");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            repository.Delete(id); 
            return RedirectToAction("Index");
        }
        public IActionResult ShowDetalis(int id)
        {
            var movie =repository.GetMovieWithDept(id);
            return View(movie);
        }
        public IActionResult Search(string name)
        {
            var movie = repository.Search(name);
            return View(movie);
        }
        [Authorize]
        public IActionResult BookTicket(int id)
        {
            var movie =repository.Get(id);
            //movies.Add(movie);
            return View(movie);
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Movie_Point.ViewModel;

namespace Movie_Point.Controllers
{
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> rolemanager;

        public RoleController(RoleManager<IdentityRole> rolemanager)
        {
            this.rolemanager = rolemanager;
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(UserRoleVM userRoleVM)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole(userRoleVM.Name);
                var result = await rolemanager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index","Home") ;
                }
                else
                {
                    ModelState.AddModelError(string.Empty,"Invalid Role");
                }
            }
            return View(userRoleVM);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movie_Point</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movie_Point.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="/images/logo.png" width="70" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Movie Point</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Cinemas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actor" asp-action="GetAll">Actors</a>
                        </li>
                        <!-- Dropdown Menu -->
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="dropdown">
                                <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                                    Actions
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <li><a class="dropdown-item" asp-action="Create" asp-controller="Movie">Create New Film</a></li>
                                    <li><a class="dropdown-item" asp-action="Create" asp-controller="Category">Create New Category</a></li>
                                    <li><a class="dropdown-item" asp-action="Create" asp-controller="Role">Create New Role</a></li>
                                    <li><a class="dropdown-item" asp-action="Create" asp-controller="Actor">Create New Actor </a></li>
                                </ul>
                            </div>
                        }
                        <!-- End Dropdown Menu -->
                    </ul>

                    <div class="d-flex">
                        <form method="get" asp-action="Search" asp-controller="Movie" class="d-flex">
                            <input name="name" class="form-control me-2 flex-grow-1" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link text-dark" asp-action="Logout" asp-controller="Account" role="button">
                                <i class="bi bi-box-arrow-in-right"></i> LogOut
                            </a>
                            <a class="nav-link text-dark" asp-action="CurrentUserDetails" asp-controller="Account" role="button">
                                <i class="bi bi-box-arrow-in-right"></i> Welcome @User.Identity.Name
                            </a>
                        }
                        else
                        {
                            <a class="nav-link text-dark" asp-action="Registeration" asp-controller="Account" role="button">
                                <i class="bi bi-person-plus-fill"></i> Register
                            </a>
                            <a class="nav-link text-dark" asp-action="Login" asp-controller="Account" role="button">
                                <i class="bi bi-box-arrow-in-right"></i> Login
                            </a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container">
            &copy; 2024 - Movie_Point - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>