Models/Movie.cs
namespace Movie_Point.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string? Description { get; set; }
        public double Price { get; set; }
        public string? ImgUrl { get; set; } 
        public string? TrailerUrl { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public MovieStatus MovieStatus { get; set; }
        public int CinemaId { get; set; }
        public int CategoryId { get; set; }
        public Cinema Cinema { get; set; }
        public Category Category { get; set; }
        public List<Actor> Actors { get; set; }
    }
}

Controllers/ActorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Movie_Point.IRepository;
using Movie_Point.Models;
using Movie_Point.ViewModel;

namespace Movie_Point.Controllers
{
    public class ActorController : Controller
    {
        IActor repository;
        public ActorController(IActor repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ShowDetails(int id) 
        { 
            var actor = repository.GetById(id);
            return View(actor); 
        }
        [HttpGet]
        public IActionResult GetAll()
        {
            var actors = repository.ReadAll();
            return View(actors);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View(new ActorViewModel());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult SaveNew(ActorViewModel actor)
        {
            if(ModelState.IsValid)
            {
                var act = new Actor();
                act.FirstName = actor.FirstName;
                act.LastName = actor.LastName;
                act.Bio = actor.Bio;
                act.ProfilePicture = actor.ProfilePicture;
                act.News = actor.News;
                repository.Create(act);
                return RedirectToAction("GetAll");
            }
            return View("Create");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var actor = repository.GetById(id);
            if (actor != null)
            {
                repository.Delete(id);
                return RedirectToAction("GetAll");
            }
            return View("Home", "Error");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var actor = repository.GetById(id);
            if (actor == null)
            {
                return View("GetAll");
            }
            ActorViewModel actorViewModel = new ActorViewModel()
            {
                LastName = actor.LastName,
                FirstName = actor.FirstName,
                Bio = actor.Bio,
                ProfilePicture = actor.ProfilePicture,
                News = actor.News
            };
            return View(actorViewModel);
        }
        //[Authorize(Roles = "Admin")]
        //public IActionResult SaveEdit(ActorViewModel actor)
        //{
        //    if (ModelState.IsValid)
        //    {
        //       var act = repository.GetById(actor.Id);
        //        repository.Update(actor);
        //        return RedirectToAction("GetAlll",act);
        //    }
        //    return View("Edit");
        //}
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Movie_Point.IRepository;
using Movie_Point.Models;
using Movie_Point.Repository;
using Movie_Point.ViewModel;

namespace Movie_Point.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        ICategory categoryRepository;
        public CategoryController(ICategory categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var categories = categoryRepository.GetAll();
            return View(categories);
        }
        [AllowAnonymous]
        public IActionResult GetMovies(int id) 
        {
            var movies = categoryRepository.GetMoviesByCatId(id);
            return View("\\Views\\Movie\\Index.cshtml", movies);
        }
        public IActionResult Create()
        {
            return View(new CategoryViewModel());
        }
        public IActionResult SaveNew(CategoryViewModel category)
        {
            if (ModelState.IsValid)
            {
                var cat = new Category();
                cat.Name = category.Name;
                categoryRepository.Create(cat);
                return RedirectToAction("Index");
            }
            return View("Create");
        }
        //public IActionResult details()
        //{
        //    var movies = categoryRepository.Details();
        //    return View(movies);
        //}
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Movie_Point.Data;
using Movie_Point.IRepository;
using Movie_Point.Models;
using Movie_Point.Repository;
using Movie_Point.ViewModel;

namespace Movie_Point.Controllers
{
    public class MovieController : Controller
    {
        //List<Movie> movies = new List<Movie>();
        IMovie repository;
        public MovieController(IMovie repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {
            var movies =repository.ReadAllWithCinema_Category();
            return View(movies);
        }
        [Authorize( Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["categories"] = repository.GetCategories();
            ViewData["cinemas"] = repository.GetCinemas();
            return View(new MovieViewModel());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult SaveNew(MovieViewModel movie)
        {
            if(ModelState.IsValid)
            {
                var mov = new Movie();
                mov.Name = movie.Name;
                mov.Description = movie.Description;
                mov.Price = movie.Price;
                mov.MovieStatus = movie.MovieStatus;
                mov.StartDate = movie.StartDate;
                mov.EndDate = movie.EndDate;
                mov.CategoryId = movie.CategoryId;
                mov.CinemaId = movie.CinemaId;
                mov.ImgUrl = movie.ImgUrl;
                mov.TrailerUrl = movie.TrailerUrl;
                repository.Create(mov);
                return RedirectToAction("Index");
            }
            return View("Create");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            var movie = repository.Get(id);
            if(movie == null)
            {
                return RedirectToAction("Index");
            }
            MovieViewModel movieViewModel = new MovieViewModel() 
            { 
                Name=movie.Name
                ,Id=movie.Id
                ,Description=movie.Description
                ,Price=movie.Price
                ,StartDate=movie.StartDate
                ,EndDate=movie.EndDate
                ,ImgUrl=movie.ImgUrl
                ,TrailerUrl=movie.TrailerUrl
                ,CategoryId=movie.CategoryId
                ,CinemaId=movie.CinemaId
                ,MovieStatus=movie.MovieStatus
            };
            ViewData["categories"] = repository.GetCategories();
            ViewData["cinemas"] = repository.GetCinemas();
            return View(movieViewModel);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult SaveEdit(MovieViewModel movie)
        {
            if (ModelState.IsValid)
            {
                var mov = repository.Get(movie.Id);
                repository.Update(movie);
                return RedirectToAction("Index",mov);
            }
            return View("Edit");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            repository.Delete(id); 
            return RedirectToAction("Index");
        }
        public IActionResult ShowDetalis(int id)
        {
            var movie =repository.GetMovieWithDept(id);
            return View(movie);
        }
        public IActionResult Search(string name)
        {
            var movie = repository.Search(name);
            return View(movie);
        }
        [Authorize]
        public IActionResult BookTicket(int id)
        {
            var movie =repository.Get(id);
            //movies.Add(movie);
            return View(movie);
        }
    }
}

Views/Movie/BookTicket.cshtml
@model Movie
<h1 class="align-content-center">Your Shopping Card</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Movie</th>
            <th scope="col">Price</th>
            <th scope="col">Subtotal</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Name</td>
            <td>@Model.Price</td>
            <td>@Model.Price</td>
            <td>
                <a asp-action="Index" asp-controller="Movie">Edit</a> || <a asp-action="Delete" asp-controller="Movie">Delete</a>
            </td>
        </tr>
    </tbody>
</table>
<button class="btn btn-outline-success" asp-action="#" asp-controller="#">Add More Items</button>
@* @model List<Movie>
<h1 class="align-content-center">Your Shopping Card</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Selected Amount</th>
            <th scope="col">Movie</th>
            <th scope="col">Price</th>
            <th scope="col">Subtotal</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        
    @{
        foreach (var Movie in Model)
        {
        <tr>
            <td></td>
            <td>@Movie.Name</td>
            <td>@Movie.Price</td>
            <td>@Movie.Price</td>
            <td>
                <a asp-action="Index" asp-controller="Movie">Edit</a> || <a asp-action="Delete" asp-controller="Movie">Delete</a>
            </td>
        </tr>
                }
            }
    </tbody>
</table>
<a class="btn btn-outline-success" asp-action="Index" asp-controller="Movie">Add More Items</a>
        
    *@

Views/Movie/Create.cshtml
<form asp-action="SaveNew" asp-controller="Movie" method="get">
	<partial name="_createeditpartial.cshtml"></partial>
	<div class="form-group">
		<button class="btn btn-primary" type="submit">Sign Up</button>
		<a asp-action="Index" asp-controller="Movie" class="btn btn-secondary float-right">Cancel</a>
	</div>
</form>
@section Scripts{
	<partial name="_ValidationScriptsPartial.cshtml"></partial>
}

Views/Movie/Edit.cshtml
<form asp-action="SaveEdit" asp-controller="Movie" method="get">
	<partial name="_createeditpartial.cshtml"></partial>
	<button type="submit">Create</button>
</form>
@section Scripts {
	<partial name="_ValidationScriptsPartial.cshtml"></partial>
}

Views/Movie/Index.cshtml
@model List<Movie>

<div class="container">
    <div class="row row-cols-3 g-4">
        @for (int i = 0; i < Model.Count; i++)
        {
            <div class="col">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <b>@Model[i].Name</b>
                        @if (User.IsInRole("Admin"))
                        {
                            <div>
                                <a asp-action="Edit" asp-controller="Movie" asp-route-id="@Model[i].Id">
                                    <i class="btn btn-outline-dark">Edit</i> <!-- Edit Icon -->
                                </a>
                            </div>
                        }
                    </div>
                    <img src="/images/movies/@Model[i].ImgUrl" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="align-bottom">Price: <span class="btn btn-outline-secondary">@Model[i].Price</span></p>
                        <p class="card-text">Cinema: @Model[i].Cinema.Name</p>
                        <p class="card-text">Star Date: @Model[i].StartDate</p>
                        <p class="card-text">End Date: @Model[i].EndDate</p>
                        <p>Category: <a asp-action="GetMovies" asp-controller="Category" asp-route-id="@Model[i].CategoryId"> <span class="btn btn-outline-primary">@Model[i].Category.Name </span></a></p>
                        <p>Status: <span class="btn btn-warning">@Model[i].MovieStatus</span> </p>
                        @* <p>Number of Views: <span>@Model[i].Views</span></p> *@
                        <a asp-action="ShowDetalis" asp-controller="Movie" asp-route-id="@Model[i].Id" class="btn btn-secondary">More Details</a>
                        <a asp-action="BookTicket" asp-controller="Movie" asp-route-id="@Model[i].Id" class="btn btn-success">Book Ticket</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Movie/Search.cshtml
@model List<Movie> 
<h1>Search Results</h1>
   <div class="container">
    <div class="row row-cols-3 g-4">
        @if (Model.Count <= 0)
        {
            <h1>NOT FOUND</h1>
        }
        else
        {
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="col">
                    <div class="card">
                        <div class="card-header d-flex justify-content-between">
                            <b>@Model[i].Name</b>
                            <div>
                                <a asp-action="Edit" asp-controller="Movie" asp-route-id="@Model[i].Id">
                                    <i class="btn btn-outline-dark">Edit</i> <!-- Edit Icon -->
                                </a>
                            </div>
                        </div>
                        <img src="/images/movies/@Model[i].ImgUrl" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="align-bottom">Price: <span class="btn btn-outline-secondary">@Model[i].Price</span></p>
                            <p class="card-text">Cinema: @Model[i].Cinema.Name</p>
                            <p class="card-text">Star Date: @Model[i].StartDate</p>
                            <p class="card-text">End Date: @Model[i].EndDate</p>
                            <p>Category: <a asp-action="GetMovies" asp-controller="Category" asp-route-id="@Model[i].CategoryId"> <span class="btn btn-outline-primary">@Model[i].Category.Name </span></a></p>
                            <p>Status: <span class="btn alert-primary">@Model[i].MovieStatus</span> </p>
                            <a asp-action="ShowDetalis" asp-controller="Movie" asp-route-id="@Model[i].Id" class="btn btn-secondary">More Details</a>
                            <a asp-action="BookTicket" asp-controller="Movie" asp-route-id="@Model[i].Id" class="btn btn-success">Book Ticket</a>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

Views/Movie/ShowDetalis.cshtml
@model Movie

    <div class="card">
        <div class="row">
            <div class="col-md-4">
                <img src="~/images/movies/@Model.ImgUrl" class="card-img-top" alt="...">
            </div>
            <div class="col-md-8">
            <div class="card-body">
                <p class="align-bottom">Price: <span class="btn btn-outline-secondary">@Model.Price</span></p>
                <p class="card-text">Cinema: @Model.Cinema.Name</p>
                <p class="card-text">Star Date: @Model.StartDate</p>
                <p class="card-text">End Date: @Model.EndDate</p><br />
                @foreach(Actor actor in Model.Actors)
                    {
                    <a asp-action="ShowDetails" asp-controller="Actor" asp-route-id="@actor.Id"><img src="/images/cast/@actor.ProfilePicture" class="rounded-circle"></img></a>
                    }<br /><br />
                <p>Category: <a asp-action="GetMovies" asp-controller="Category" asp-route-id="@Model.CategoryId"> <span class="btn btn-outline-primary">@Model.Category.Name </span></a></p>
                <p>Satus:<span class="btn btn-warning">@Model.MovieStatus</span> </p>
                <a asp-action="BookTicket" asp-controller="Movie" class="btn btn-success ">Book Ticket</a>
            </div>
        </div>
    </div>

Views/Movie/_CreateEditPartial.cshtml
@using Movie_Point.ViewModel
@model MovieViewModel
@{
	SelectList Categories = new SelectList(ViewBag.categories, "CategoryId", "Name");
	SelectList Cinemas = new SelectList(ViewBag.cinemas, "CinemaId", "Name");
}

<input type="hidden" asp-for="Id" />

<label asp-for="Name"></label>
<input asp-for="Name" class="form-control" />
<span asp-validation-for="Name"></span>
<br />

<label asp-for="CategoryId"></label>
<select asp-items="Categories" asp-for="CategoryId" class="form-control"></select>
<span asp-validation-for="CategoryId"></span>
<br />

<label asp-for="CinemaId"></label>
<select asp-items="Cinemas" asp-for="CinemaId" class="form-control"></select>
<span asp-validation-for="CinemaId"></span>
<br />

<label asp-for="Description"></label>
<input asp-for="Description" class="form-control" />
<span asp-validation-for="Description"></span>
<br />

<label asp-for="Price"></label>
<input asp-for="Price" class="form-control" />
<span asp-validation-for="Price"></span>
<br />

<label asp-for="ImgUrl"></label>
<input asp-for="ImgUrl" class="form-control" />
<span asp-validation-for="ImgUrl"></span>
<br />

<label asp-for="TrailerUrl"></label>
<input asp-for="TrailerUrl" class="form-control" />
<span asp-validation-for="TrailerUrl"></span>
<br />

<label asp-for="StartDate"></label>
<input asp-for="StartDate" class="form-control" />
<span asp-validation-for="StartDate"></span>
<br />

<label asp-for="EndDate"></label>
<input asp-for="EndDate" class="form-control" />
<span asp-validation-for="EndDate"></span>
<br />